name: hash-build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.6]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: CI=false yarn build-ci
      - name: Install IPFS & Hash
        run: |
          # make file runnable, might not be necessary
          chmod +x "${GITHUB_WORKSPACE}/.github/ipfs-install-and-hash.sh"
          # run script
          "${GITHUB_WORKSPACE}/.github/ipfs-install-and-hash.sh"
