name: Integration tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  synpress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        node-version: [16.13.0]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Cypress cache
        id: cypress-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
          key: cypress-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            cypress-cache

      - name: Install dependencies
        run: yarn

      - name: Disable Cypress warnings
        run: |
          echo -e 'pcm.!default {\n type hw\n card 0\n}\n\nctl.!default {\n type hw\n card 0\n}' > ~/.asoundrc

      - name: Run Synpress
        run: yarn run test:e2e

