name: Integration tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  cypress-run:
    # TODO: Add some condition if we don't want to trigger this on every pr. (maybe some flag)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        node-version: [16.13.0]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Cypress cache
        id: cypress-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
          key: cypress-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            cypress-cache

      - name: Install dependencies
        run: yarn

      - name: Disable Cypress warnings
        run: |
          echo -e 'pcm.!default {\n type hw\n card 0\n}\n\nctl.!default {\n type hw\n card 0\n}' > ~/.asoundrc

      - name: Create Cypress Directories for Artifacts
        run: mkdir -p cypress/screenshots && mkdir -p cypress/videos

      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          NODE_ENV: 'development'
        with:
          browser: chrome
          headless: true
          start: yarn start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 300
